# Generated by Django 3.2 on 2022-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='id_card',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.BigIntegerField(),
        ),
    ]
